#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html//index.nginx-debian.html
change="a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _/$change" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
n_str="a error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}"
sudo sed -i "/server_name _/$n_str" /etc/nginx/sites-available/default
sudo service nginx restart
