#!/usr/bin/env bash
# This script printing Holberton School 10 times
# But 4th print bad luck and 8th print good luck
i=0
while((i<10));
do
	if((i==3));
	then
	        echo bad luck
	elif((i==7));
	then
		echo good luck
	else
		echo Holberton School
	fi
	i=$((i+1))
done
